language: elixir
elixir: '1.5'
otp_release: '20.0'
addons:
  postgresql: '9.5'
services:
  - postgresql
before_install:
  - export MIX_ENV=test
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test
  - mix credo
